### ISSUE TITLE
Option for a "silent" execution

### ISSUE THREAD

**Issue by dcfidalgo** [halirutan/VariableDensitySubsampling#2]
Hey @halirutan, last week I was implementing this package in Kornelius code. I noticed that when calling `PoissonSampling(...).subsample()` some information is printed, which is a bit annoying when using it in a training loop for example.
Would it be possible to include a `verbose` or `silent` argument in the `subsample` method to get a completely silent execution?

**Comment by halirutan** [comment]
Maybe you have a better idea, but the only reasonable way I saw was to redirect `stdout` to `/dev/null` when calling a library function.

My best-case idea would have been if there is an easy way to use a real logger in the C library which is directly turned into (real) `logging` calls in Python. However, I didn't see an easy way to do this. I want to keep the library clean of pybind code and all things I found would have been a lot of work to silence a few `printf` calls.

Please see pull request #3

**Comment by dcfidalgo** [comment]
Thanks a lot! I think the solution is perfectly fine for our use case, I certainly don't know how to improve it ...

**Comment by halirutan** [comment]
Fixed and merged
