### ISSUE TITLE
'logging' flag not working

### ISSUE THREAD

**Issue by dcfidalgo** [halirutan/VariableDensitySubsampling#4]
Hey @halirutan! I just tried out the two new arguments (`random_seed` and `logging`), and they seem to work fine. I just noticed that you cannot activate the output anymore, setting `logging=True` seems to have no effect. I think we must propagate the `logging` variable to the `StdoutRedirector` [here](https://github.com/halirutan/VariableDensitySubsampling/blob/main/src/PoissonSubsampling.cpp#L94), [here](https://github.com/halirutan/VariableDensitySubsampling/blob/main/src/PoissonSubsampling.cpp#L105) and [here](https://github.com/halirutan/VariableDensitySubsampling/blob/main/src/PoissonSubsampling.cpp#L132)
Let me know if you want me to provide a PR for this!

**Comment by halirutan** [comment]
Well, in my defense, the comment in line 43 was already written 🤣 

https://github.com/halirutan/VariableDensitySubsampling/blob/bbc52e0b125fe6ca08e357c2db9a059d5eab7ea8/src/PoissonSubsampling.cpp#L43
